-- begin TRAINING_CONTRACT
alter table TRAINING_CONTRACT add constraint FK_TRAINING_CONTRACT_ON_CUSTOMER foreign key (CUSTOMER_ID) references TRAINING_ORGANIZATION(ID)^
alter table TRAINING_CONTRACT add constraint FK_TRAINING_CONTRACT_ON_PERFORMER foreign key (PERFORMER_ID) references TRAINING_ORGANIZATION(ID)^
alter table TRAINING_CONTRACT add constraint FK_TRAINING_CONTRACT_ON_CUSTOMER_SIGNER foreign key (CUSTOMER_SIGNER_ID) references SEC_USER(ID)^
alter table TRAINING_CONTRACT add constraint FK_TRAINING_CONTRACT_ON_STATUS foreign key (STATUS_ID) references TRAINING_STATUS(ID)^
alter table TRAINING_CONTRACT add constraint FK_TRAINING_CONTRACT_ON_PERFORMER_SIGNER foreign key (PERFORMER_SIGNER_ID) references SEC_USER(ID)^
create index IDX_TRAINING_CONTRACT_ON_CUSTOMER on TRAINING_CONTRACT (CUSTOMER_ID)^
create index IDX_TRAINING_CONTRACT_ON_PERFORMER on TRAINING_CONTRACT (PERFORMER_ID)^
create index IDX_TRAINING_CONTRACT_ON_CUSTOMER_SIGNER on TRAINING_CONTRACT (CUSTOMER_SIGNER_ID)^
create index IDX_TRAINING_CONTRACT_ON_STATUS on TRAINING_CONTRACT (STATUS_ID)^
create index IDX_TRAINING_CONTRACT_ON_PERFORMER_SIGNER on TRAINING_CONTRACT (PERFORMER_SIGNER_ID)^
-- end TRAINING_CONTRACT
-- begin TRAINING_CONTRACT_FILE_DESCRIPTOR_LINK
alter table TRAINING_CONTRACT_FILE_DESCRIPTOR_LINK add constraint FK_CONFILDES_ON_CONTRACT foreign key (CONTRACT_ID) references TRAINING_CONTRACT(ID)^
alter table TRAINING_CONTRACT_FILE_DESCRIPTOR_LINK add constraint FK_CONFILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end TRAINING_CONTRACT_FILE_DESCRIPTOR_LINK
-- begin TRAINING_STAGE
alter table TRAINING_STAGE add constraint FK_TRAINING_STAGE_ON_INVOICE foreign key (INVOICE_ID) references TRAINING_INVOICE(ID)^
alter table TRAINING_STAGE add constraint FK_TRAINING_STAGE_ON_SERVICE_COMPLETION_CERTIFICATE foreign key (SERVICE_COMPLETION_CERTIFICATE_ID) references TRAINING_SERVICE_COMPLETION_CERTIFICATE(ID)^
alter table TRAINING_STAGE add constraint FK_TRAINING_STAGE_ON_CONTRACT foreign key (CONTRACT_ID) references TRAINING_CONTRACT(ID)^
create index IDX_TRAINING_STAGE_ON_INVOICE on TRAINING_STAGE (INVOICE_ID)^
create index IDX_TRAINING_STAGE_ON_SERVICE_COMPLETION_CERTIFICATE on TRAINING_STAGE (SERVICE_COMPLETION_CERTIFICATE_ID)^
create index IDX_TRAINING_STAGE_ON_CONTRACT on TRAINING_STAGE (CONTRACT_ID)^
-- end TRAINING_STAGE
