alter table TRAINING_CONTRACT add constraint FK_TRAINING_CONTRACT_ON_PERFORMER_SIGNER foreign key (PERFORMER_SIGNER_ID) references SEC_USER(ID);
create index IDX_TRAINING_CONTRACT_ON_PERFORMER_SIGNER on TRAINING_CONTRACT (PERFORMER_SIGNER_ID);
