alter table TRAINING_CONTRACT add constraint FK_TRAINING_CONTRACT_ON_CUSTOMER foreign key (CUSTOMER_ID) references TRAINING_ORGANIZATION(ID);
alter table TRAINING_CONTRACT add constraint FK_TRAINING_CONTRACT_ON_PERFORMER foreign key (PERFORMER_ID) references TRAINING_ORGANIZATION(ID);
create index IDX_TRAINING_CONTRACT_ON_CUSTOMER on TRAINING_CONTRACT (CUSTOMER_ID);
create index IDX_TRAINING_CONTRACT_ON_PERFORMER on TRAINING_CONTRACT (PERFORMER_ID);
