alter table TRAINING_CONTRACT add constraint FK_TRAINING_CONTRACT_ON_STATUS foreign key (STATUS_ID) references TRAINING_STATUS(ID);
create index IDX_TRAINING_CONTRACT_ON_STATUS on TRAINING_CONTRACT (STATUS_ID);
