alter table TRAINING_STAGE add constraint FK_TRAINING_STAGE_ON_CONTRACT foreign key (CONTRACT_ID) references TRAINING_CONTRACT(ID);
create index IDX_TRAINING_STAGE_ON_CONTRACT on TRAINING_STAGE (CONTRACT_ID);
