alter table TRAINING_CONTRACT add constraint FK_TRAINING_CONTRACT_ON_CUSTOMER_SIGNER foreign key (CUSTOMER_SIGNER_ID) references SEC_USER(ID);
create index IDX_TRAINING_CONTRACT_ON_CUSTOMER_SIGNER on TRAINING_CONTRACT (CUSTOMER_SIGNER_ID);
